# Generated by Django 5.0 on 2023-12-16 04:49

import custome_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custome_app', '0003_remove_item_text_alter_address_lattitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='custom_text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='font',
        ),
        migrations.RemoveField(
            model_name='item',
            name='logo',
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='custom_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custome_app.font'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=custome_app.models.upload_to),
        ),
    ]
