# Generated by Django 5.0 on 2023-12-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custome_app', '0004_remove_item_custom_text_remove_item_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='custome_app.address'),
        ),
    ]
